[package]
name = "stereokit"
version = "0.4.2"
edition = "2021"
description = "Higher-Level wrapper around stereokit-sys bindings for StereoKitC library for XR"
homepage = "https://stereokit.net/"
keywords = ["stereokit", "XR", "VR", "AR"]
license = "MIT"
repository = "https://github.com/MalekiRe/stereokit-rs"

exclude = [
    ".idea"
]

[features]
default = []
linux-egl = ["stereokit-sys/linux-egl"]
bevy = ["bevy_ecs"]


[dependencies]
mint = "0.5.9"
prisma = "0.1.1"
num = "0.4.0"
num-derive = "0.3.3"
num-traits = "0.2.15"
derive_is_enum_variant = "0.1.1"
derive_builder = "0.11.2"
stereokit-sys = "1.0.3"
once_cell = "1.13.0"
bitflags = "1.3.2"
ustr = "0.9.0"
bevy_ecs = {version = "0.8.1", optional = true}
serde = { version = "1.0.145", features = ["derive"] }
serde_repr = "0.1.9"
bitflags_serde_shim = "0.2.2"
num_enum = "0.5.7"

[dev-dependencies]
anyhow = "1.0.61"
glam = {version = "0.21.3", features = ["mint"]}
