[package]
name = "stereokit-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stereokit-sys = "0.1.0"
mint = {verions = "0.5.9"}
prisma = "0.1.1"