[package]
name = "stereokit"
version = "0.15.3"
edition = "2021"
description = "Higher-Level wrapper around stereokit-sys bindings for StereoKitC library for XR"
homepage = "https://stereokit.net/"
keywords = ["stereokit", "XR", "VR", "AR"]
license = "MIT"
repository = "https://github.com/MalekiRe/stereokit-rs"

[lib]
crate-type = ["lib", "cdylib"]

[features]
default = []
physics = ["stereokit-sys/physics"]
linux-egl = ["stereokit-sys/linux-egl"]
high-level = ["glam"]
prisma = ["stereokit-sys/prisma"]
color_named = []
glam = ["dep:glam"]
serde = []

[dependencies]
mint = { version = "0.5.9", features = ["serde"] }
num-derive = "0.3.3"
derive_is_enum_variant = "0.1.1"
derive_builder = "0.12.0"
stereokit-sys = "2.4.2"
once_cell = "1.17.1"
bitflags = "1.3.2"
ustr = "0.9.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_repr = "0.1.10"
bitflags_serde_shim = "0.2.4"
num_enum = "0.6.0"
glam = {version = "0.23.0", features = ["mint"], optional = true}
color-eyre = "0.6.2"
tracing = "0.1.37"

[target.'cfg(target_os = "android")'.dependencies]
ndk-context = "0.1.1"

[dev-dependencies]
glam = {version = "0.23.0", features = ["mint"]}
tracing-subscriber = "0.3.16"

[profile.dev.package.backtrace]
opt-level = 3
